fstats:
  target: dev
  outputs:
    dev:
      type: greenplum
      host: localhost
      user: greenplum
      password: greenplum123
      port: 6432
      dbname: greenplum
      schema: public
      threads: 3
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds